"""add command

Revision ID: 1429815b8232
Revises: ec59cff9a11d
Create Date: 2023-05-20 16:32:05.016110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1429815b8232'
down_revision = 'ec59cff9a11d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('request', sa.TEXT(), nullable=False),
    sa.Column('response', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('command')
    # ### end Alembic commands ###