"""add cascade for command

Revision ID: 6fb92e316c13
Revises: 1429815b8232
Create Date: 2023-05-23 11:34:14.353206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb92e316c13'
down_revision = '1429815b8232'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###