"""remove relationship from commands

Revision ID: bc65f24d78d4
Revises: c00ed4a71ce0
Create Date: 2023-05-23 11:38:30.168462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc65f24d78d4'
down_revision = 'c00ed4a71ce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###