"""add cascade for command

Revision ID: c00ed4a71ce0
Revises: 6fb92e316c13
Create Date: 2023-05-23 11:37:25.779768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00ed4a71ce0'
down_revision = '6fb92e316c13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###